// Package main demonstrates peer-to-peer communication using the Tor transport.
// This example can run as either a listener or dialer.
//
// Listener mode (no arguments):
//
//	go run ./examples/tor-peer-example
//
// Dialer mode (provide peer's multiaddr):
//
//	go run ./examples/tor-peer-example <multiaddr>
//
// Prerequisites: Tor daemon running on localhost:9050
package main

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"log"
	"os"
	"time"

	"github.com/go-i2p/go-libp2p-transport-onramp/tor"
	"github.com/libp2p/go-libp2p"
	"github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/core/transport"
	ma "github.com/multiformats/go-multiaddr"
)

const protocolID = "/tor-example/1.0.0"

func main() {
	ctx := context.Background()

	// Determine mode based on command-line arguments
	isDialer := len(os.Args) > 1

	if isDialer {
		runDialer(ctx, os.Args[1])
	} else {
		runListener(ctx)
	}
}

// runListener creates a host, starts listening, and waits for connections
func runListener(ctx context.Context) {
	log.Println("Starting listener mode...")

	// Create a listen multiaddr for Tor
	// The actual onion address will be generated by the transport
	listenAddr, err := ma.NewMultiaddr("/onion3/0.0.0.0:0")
	if err != nil {
		log.Fatalf("Failed to create listen address: %v", err)
	}

	// Create libp2p host with Tor transport and listen on Tor
	h, err := libp2p.New(
		libp2p.Transport(func(upgrader transport.Upgrader, rcmgr network.ResourceManager) (transport.Transport, error) {
			return tor.NewTransport(upgrader, rcmgr)
		}),
		libp2p.ListenAddrs(listenAddr),
	)
	if err != nil {
		log.Fatalf("Failed to create libp2p host: %v", err)
	}
	defer h.Close()

	// Set up stream handler to respond to incoming connections
	h.SetStreamHandler(protocolID, func(s network.Stream) {
		defer s.Close()
		log.Printf("Received connection from peer: %s", s.Conn().RemotePeer())

		// Read incoming message
		reader := bufio.NewReader(s)
		msg, err := reader.ReadString('\n')
		if err != nil && err != io.EOF {
			log.Printf("Error reading from stream: %v", err)
			return
		}
		log.Printf("Received message: %s", msg)

		// Send response
		response := "Hello from Tor listener!\n"
		if _, err := s.Write([]byte(response)); err != nil {
			log.Printf("Error writing response: %v", err)
			return
		}
		log.Println("Sent response")
	})

	// Get the listen addresses
	addrs := h.Addrs()
	if len(addrs) == 0 {
		log.Fatal("No listen addresses found")
	}

	fmt.Printf("\n=== Tor Listener Ready ===\n")
	fmt.Printf("Peer ID: %s\n", h.ID())
	fmt.Printf("Listen Addresses:\n")
	for _, addr := range addrs {
		peerAddr := addr.Encapsulate(ma.StringCast("/p2p/" + h.ID().String()))
		fmt.Printf("  %s\n", peerAddr)
		fmt.Printf("\nTo connect from another peer, run:\n")
		fmt.Printf("  go run ./examples/tor-peer-example %s\n", peerAddr)
	}
	fmt.Println("\nWaiting for connections... (press Ctrl+C to exit)")

	// Keep running until interrupted
	select {}
}

// runDialer creates a host and connects to the specified peer
func runDialer(ctx context.Context, targetAddr string) {
	log.Printf("Starting dialer mode, connecting to: %s", targetAddr)

	// Parse the target multiaddr
	maddr, err := ma.NewMultiaddr(targetAddr)
	if err != nil {
		log.Fatalf("Invalid multiaddr: %v", err)
	}

	// Extract peer info from multiaddr
	peerInfo, err := peer.AddrInfoFromP2pAddr(maddr)
	if err != nil {
		log.Fatalf("Failed to parse peer info: %v", err)
	}

	// Create libp2p host with Tor transport
	h, err := libp2p.New(
		libp2p.Transport(func(upgrader transport.Upgrader, rcmgr network.ResourceManager) (transport.Transport, error) {
			return tor.NewTransport(upgrader, rcmgr)
		}),
		libp2p.NoListenAddrs,
	)
	if err != nil {
		log.Fatalf("Failed to create libp2p host: %v", err)
	}
	defer h.Close()

	fmt.Printf("\n=== Tor Dialer ===\n")
	fmt.Printf("Peer ID: %s\n", h.ID())
	fmt.Printf("Target: %s\n\n", peerInfo.ID)

	// Connect to the peer (with timeout)
	connectCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	log.Println("Connecting to peer over Tor (this may take a minute)...")
	if err := h.Connect(connectCtx, *peerInfo); err != nil {
		log.Fatalf("Failed to connect: %v", err)
	}
	log.Println("Connected successfully!")

	// Open a stream
	log.Printf("Opening stream with protocol: %s", protocolID)
	stream, err := h.NewStream(ctx, peerInfo.ID, protocolID)
	if err != nil {
		log.Fatalf("Failed to open stream: %v", err)
	}
	defer stream.Close()

	// Send a message
	message := "Hello from Tor dialer!\n"
	log.Printf("Sending message: %s", message)
	if _, err := stream.Write([]byte(message)); err != nil {
		log.Fatalf("Failed to write to stream: %v", err)
	}

	// Read response
	log.Println("Waiting for response...")
	reader := bufio.NewReader(stream)
	response, err := reader.ReadString('\n')
	if err != nil && err != io.EOF {
		log.Fatalf("Failed to read response: %v", err)
	}

	fmt.Printf("\n=== Communication Successful ===\n")
	fmt.Printf("Sent: %s", message)
	fmt.Printf("Received: %s\n", response)
	fmt.Println("\nPeer-to-peer communication over Tor completed successfully!")
}
